INSERT INTO products (id, name, calories, units, created_at, updated_at) VALUES
(1, 'Apple', 52, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Banana', 89, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Milk', 42, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Sugar', 387, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Orange', 47, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Rice', 130, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Bread', 265, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Cheese', 402, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Tomato', 18, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Potato', 77, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Onion', 40, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'Carrot', 41, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'Cucumber', 16, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'Lettuce', 15, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'Spinach', 23, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'Broccoli', 34, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'Chicken Breast', 165, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'Beef', 250, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'Pork', 242, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'Salmon', 208, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'Tuna', 132, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Egg', 155, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 'Yogurt', 59, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'Butter', 717, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 'Olive Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'Sunflower Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 'Salt', 0, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'Pepper', 251, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 'Garlic', 149, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'Ginger', 80, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 'Honey', 304, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 'Jam', 278, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 'Pasta', 131, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Noodles', 138, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Flour', 364, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 'Corn', 86, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 'Peas', 81, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 'Beans', 347, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Lentils', 116, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 'Chickpeas', 164, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 'Coconut', 354, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 'Avocado', 160, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 'Strawberry', 32, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 'Blueberry', 57, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 'Raspberry', 52, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 'Blackberry', 43, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 'Watermelon', 30, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 'Melon', 34, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 'Pineapple', 50, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 'Grapes', 69, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(51, 'Cherry', 50, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 'Pear', 57, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 'Kiwi', 41, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 'Mango', 60, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 'Papaya', 43, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 'Fig', 74, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 'Date', 282, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(58, 'Plum', 46, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Apricot', 48, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 'Nectarine', 44, 'pcs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 'Cabbage', 25, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 'Zucchini', 17, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(63, 'Celery', 16, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 'Mushroom', 22, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 'Pumpkin', 26, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 'Sweet Potato', 86, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 'Artichoke', 47, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 'Asparagus', 20, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 'Radish', 16, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 'Turnip', 28, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(71, 'Brussels Sprout', 43, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(72, 'Leek', 31, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(73, 'Parsnip', 75, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(74, 'Cauliflower', 25, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(75, 'Beetroot', 43, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(76, 'Kale', 49, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(77, 'Arugula', 25, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(78, 'Basil', 23, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(79, 'Parsley', 36, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(80, 'Coriander', 23, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(81, 'Thyme', 101, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(82, 'Rosemary', 131, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(83, 'Mint', 44, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(84, 'Oregano', 265, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(85, 'Sage', 315, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(86, 'Clove', 274, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(87, 'Cinnamon', 247, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, 'Nutmeg', 525, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(89, 'Vanilla', 288, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(90, 'Cocoa', 228, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(91, 'Chocolate', 546, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(92, 'Coffee', 2, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(93, 'Tea', 1, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(94, 'Soda', 41, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(95, 'Juice', 45, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, 'Water', 0, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(97, 'Beer', 43, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(98, 'Wine', 85, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(99, 'Whiskey', 250, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 'Vodka', 231, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(101, 'Gin', 263, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 'Rum', 231, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 'Tofu', 76, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 'Tempeh', 193, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 'Seitan', 370, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 'Almond', 579, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 'Cashew', 553, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 'Walnut', 654, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(109, 'Pistachio', 562, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110, 'Hazelnut', 628, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(111, 'Peanut', 567, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(112, 'Chia Seed', 486, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(113, 'Flax Seed', 534, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(114, 'Pumpkin Seed', 559, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(115, 'Sunflower Seed', 584, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(116, 'Quinoa', 120, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(117, 'Couscous', 112, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(118, 'Barley', 354, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(119, 'Buckwheat', 343, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120, 'Oats', 389, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(121, 'Millet', 378, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(122, 'Rye', 335, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(123, 'Spelt', 338, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(124, 'Farro', 340, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(125, 'Wheat Germ', 360, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(126, 'Wheat Bran', 216, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(127, 'Cornmeal', 370, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(128, 'Polenta', 358, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(129, 'Tapioca', 358, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130, 'Arrowroot', 357, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(131, 'Gelatin', 362, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(132, 'Agar', 306, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(133, 'Miso', 199, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(134, 'Natto', 212, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(135, 'Kimchi', 15, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(136, 'Sauerkraut', 27, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(137, 'Pickles', 11, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(138, 'Mustard', 66, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(139, 'Ketchup', 112, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140, 'Mayonnaise', 680, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(141, 'Vinegar', 21, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(142, 'Soy Sauce', 53, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(143, 'Hot Sauce', 12, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(144, 'BBQ Sauce', 130, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(145, 'Pesto', 303, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(146, 'Hummus', 166, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(147, 'Guacamole', 155, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(148, 'Salsa', 36, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(149, 'Relish', 97, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150, 'Tapenade', 239, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(151, 'Tzatziki', 59, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(152, 'Raita', 60, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(153, 'Rice Cake', 387, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(154, 'Puffed Wheat', 367, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(155, 'Bran Flakes', 275, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(156, 'Granola', 489, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(157, 'Muesli', 389, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(158, 'Protein Bar', 350, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(159, 'Energy Drink', 45, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(160, 'Protein Powder', 400, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(161, 'Whey Protein', 412, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(162, 'Plant Protein', 390, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(163, 'Cereal Bar', 321, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(164, 'Trail Mix', 462, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(165, 'Dried Apricot', 241, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(166, 'Raisin', 299, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(167, 'Prune', 240, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(168, 'Dried Fig', 249, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(169, 'Cranberry', 325, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(170, 'Date Paste', 310, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(171, 'Molasses', 290, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(172, 'Maple Syrup', 260, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(173, 'Agave Syrup', 310, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(174, 'Cane Sugar', 387, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(175, 'Brown Sugar', 380, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(176, 'Icing Sugar', 389, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(177, 'Coconut Sugar', 375, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(178, 'Palm Sugar', 386, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(179, 'Stevia', 0, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(180, 'Erythritol', 20, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(181, 'Xylitol', 240, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(182, 'Sorbitol', 250, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(183, 'Aspartame', 4, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(184, 'Sucralose', 0, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(185, 'Monk Fruit', 0, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(186, 'Yacon Syrup', 133, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(187, 'Ghee', 876, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(188, 'Lard', 902, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(189, 'Shortening', 900, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(190, 'Tallow', 902, 'g', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(191, 'Coconut Oil', 892, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(192, 'Palm Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(193, 'Canola Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(194, 'Avocado Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(195, 'Grapeseed Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(196, 'Sesame Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(197, 'Walnut Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(198, 'Almond Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(199, 'Macadamia Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(200, 'Hemp Oil', 884, 'ml', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO translations (field_name, language, translatable_id, translatable_type, value)
VALUES
('name', 'EN',1, 'PRODUCT', 'Apple'),
('name', 'LT',1, 'PRODUCT', 'Obuolys'),
('name', 'EN',2, 'PRODUCT', 'Banana'),
('name', 'LT',2, 'PRODUCT', 'Bananas'),
('name', 'EN',3, 'PRODUCT', 'Milk'),
('name', 'LT',3, 'PRODUCT', 'Pienas'),
('name', 'EN',4, 'PRODUCT', 'Sugar'),
('name', 'LT',4, 'PRODUCT', 'Cukrus'),
('name', 'EN',5, 'PRODUCT', 'Orange'),
('name', 'LT',5, 'PRODUCT', 'Apelsinas'),
('name', 'EN',6, 'PRODUCT', 'Rice'),
('name', 'LT',6, 'PRODUCT', 'Ryžiai'),
('name', 'EN',7, 'PRODUCT', 'Bread'),
('name', 'LT',7, 'PRODUCT', 'Duona'),
('name', 'EN',8, 'PRODUCT', 'Cheese'),
('name', 'LT',8, 'PRODUCT', 'Sūris'),
('name', 'EN',9, 'PRODUCT', 'Tomato'),
('name', 'LT',9, 'PRODUCT', 'Pomidoras'),
('name', 'EN',10, 'PRODUCT', 'Potato'),
('name', 'LT',10, 'PRODUCT', 'Bulvė'),
('name', 'EN',11, 'PRODUCT', 'Onion'),
('name', 'LT',11, 'PRODUCT', 'Svogūnas'),
('name', 'EN',12, 'PRODUCT', 'Carrot'),
('name', 'LT',12, 'PRODUCT', 'Morka'),
('name', 'EN',13, 'PRODUCT', 'Cucumber'),
('name', 'LT',13, 'PRODUCT', 'Agurkas'),
('name', 'EN',14, 'PRODUCT', 'Lettuce'),
('name', 'LT',14, 'PRODUCT', 'Salota'),
('name', 'EN',15, 'PRODUCT', 'Spinach'),
('name', 'LT',15, 'PRODUCT', 'Špinatai'),
('name', 'EN',16, 'PRODUCT', 'Broccoli'),
('name', 'LT',16, 'PRODUCT', 'Brokoliai'),
('name', 'EN',17, 'PRODUCT', 'Chicken Breast'),
('name', 'LT',17, 'PRODUCT', 'Vištienos krūtinėlė'),
('name', 'EN',18, 'PRODUCT', 'Beef'),
('name', 'LT',18, 'PRODUCT', 'Jautiena'),
('name', 'EN',19, 'PRODUCT', 'Pork'),
('name', 'LT',19, 'PRODUCT', 'Kiauliena'),
('name', 'EN',20, 'PRODUCT', 'Salmon'),
('name', 'LT',20, 'PRODUCT', 'Lašiša'),
('name', 'EN',21, 'PRODUCT', 'Tuna'),
('name', 'LT',21, 'PRODUCT', 'Tunas'),
('name', 'EN',22, 'PRODUCT', 'Egg'),
('name', 'LT',22, 'PRODUCT', 'Kiaušinis'),
('name', 'EN',23, 'PRODUCT', 'Yogurt'),
('name', 'LT',23, 'PRODUCT', 'Jogurtas'),
('name', 'EN',24, 'PRODUCT', 'Butter'),
('name', 'LT',24, 'PRODUCT', 'Sviestas'),
('name', 'EN',25, 'PRODUCT', 'Olive Oil'),
('name', 'LT',25, 'PRODUCT', 'Alyvuogių aliejus'),
('name', 'EN',26, 'PRODUCT', 'Sunflower Oil'),
('name', 'LT',26, 'PRODUCT', 'Saulėgrąžų aliejus'),
('name', 'EN',27, 'PRODUCT', 'Salt'),
('name', 'LT',27, 'PRODUCT', 'Druska'),
('name', 'EN',28, 'PRODUCT', 'Pepper'),
('name', 'LT',28, 'PRODUCT', 'Pipirai'),
('name', 'EN',29, 'PRODUCT', 'Garlic'),
('name', 'LT',29, 'PRODUCT', 'Česnakas'),
('name', 'EN',30, 'PRODUCT', 'Ginger'),
('name', 'LT',30, 'PRODUCT', 'Imbieras'),
('name', 'EN',31, 'PRODUCT', 'Honey'),
('name', 'LT',31, 'PRODUCT', 'Medus'),
('name', 'EN',32, 'PRODUCT', 'Jam'),
('name', 'LT',32, 'PRODUCT', 'Uogienė'),
('name', 'EN',33, 'PRODUCT', 'Pasta'),
('name', 'LT',33, 'PRODUCT', 'Makaronai'),
('name', 'EN',34, 'PRODUCT', 'Noodles'),
('name', 'LT',34, 'PRODUCT', 'Makaronai'),
('name', 'EN',35, 'PRODUCT', 'Flour'),
('name', 'LT',35, 'PRODUCT', 'Miltai'),
('name', 'EN',36, 'PRODUCT', 'Corn'),
('name', 'LT',36, 'PRODUCT', 'Kukurūzai'),
('name', 'EN',37, 'PRODUCT', 'Peas'),
('name', 'LT',37, 'PRODUCT', 'Žirniai'),
('name', 'EN',38, 'PRODUCT', 'Beans'),
('name', 'LT',38, 'PRODUCT', 'Pupelės'),
('name', 'EN',39, 'PRODUCT', 'Lentils'),
('name', 'LT',39, 'PRODUCT', 'Lęšiai'),
('name', 'EN',40, 'PRODUCT', 'Chickpeas'),
('name', 'LT',40, 'PRODUCT', 'Avinžirniai'),
('name', 'EN',41, 'PRODUCT', 'Coconut'),
('name', 'LT',41, 'PRODUCT', 'Kokosas'),
('name', 'EN',42, 'PRODUCT', 'Avocado'),
('name', 'LT',42, 'PRODUCT', 'Avokadas'),
('name', 'EN',43, 'PRODUCT', 'Strawberry'),
('name', 'LT',43, 'PRODUCT', 'Braške'),
('name', 'EN',44, 'PRODUCT', 'Blueberry'),
('name', 'LT',44, 'PRODUCT', 'Mėlynė'),
('name', 'EN',45, 'PRODUCT', 'Raspberry'),
('name', 'LT',45, 'PRODUCT', 'Avietė'),
('name', 'EN',46, 'PRODUCT', 'Blackberry'),
('name', 'LT',46, 'PRODUCT', 'Gervuogė'),
('name', 'EN',47, 'PRODUCT', 'Watermelon'),
('name', 'LT',47, 'PRODUCT', 'Arbūzas'),
('name', 'EN',48, 'PRODUCT', 'Melon'),
('name', 'LT',48, 'PRODUCT', 'Melionas'),
('name', 'EN',49, 'PRODUCT', 'Pineapple'),
('name', 'LT',49, 'PRODUCT', 'Ananasas'),
('name', 'EN',50, 'PRODUCT', 'Grapes'),
('name', 'LT',50, 'PRODUCT', 'Vynuogės'),
('name', 'EN',51, 'PRODUCT', 'Cherry'),
('name', 'LT',51, 'PRODUCT', 'Vyšnia'),
('name', 'EN',52, 'PRODUCT', 'Pear'),
('name', 'LT',52, 'PRODUCT', 'Kriausė'),
('name', 'EN',53, 'PRODUCT', 'Kiwi'),
('name', 'LT',53, 'PRODUCT', 'Kivis'),
('name', 'EN',54, 'PRODUCT', 'Mango'),
('name', 'LT',54, 'PRODUCT', 'Mangas'),
('name', 'EN',55, 'PRODUCT', 'Papaya'),
('name', 'LT',55, 'PRODUCT', 'Papaja'),
('name', 'EN',56, 'PRODUCT', 'Fig'),
('name', 'LT',56, 'PRODUCT', 'Figa'),
('name', 'EN',57, 'PRODUCT', 'Date'),
('name', 'LT',57, 'PRODUCT', 'Datulė'),
('name', 'EN',58, 'PRODUCT', 'Plum'),
('name', 'LT',58, 'PRODUCT', 'Slyva'),
('name', 'EN',59, 'PRODUCT', 'Apricot'),
('name', 'LT',59, 'PRODUCT', 'Abrikosas'),
('name', 'EN',60, 'PRODUCT', 'Nectarine'),
('name', 'LT',60, 'PRODUCT', 'Nektarinas'),
('name', 'EN',61, 'PRODUCT', 'Cabbage'),
('name', 'LT',61, 'PRODUCT', 'Kopūstas'),
('name', 'EN',62, 'PRODUCT', 'Zucchini'),
('name', 'LT',62, 'PRODUCT', 'Cukinija'),
('name', 'EN',63, 'PRODUCT', 'Celery'),
('name', 'LT',63, 'PRODUCT', 'Salieras'),
('name', 'EN',64, 'PRODUCT', 'Mushroom'),
('name', 'LT',64, 'PRODUCT', 'Grybas'),
('name', 'EN',65, 'PRODUCT', 'Pumpkin'),
('name', 'LT',65, 'PRODUCT', 'Moliūgas'),
('name', 'EN',66, 'PRODUCT', 'Sweet Potato'),
('name', 'LT',66, 'PRODUCT', 'Saldžioji bulvė'),
('name', 'EN',67, 'PRODUCT', 'Artichoke'),
('name', 'LT',67, 'PRODUCT', 'Artišokas'),
('name', 'EN',68, 'PRODUCT', 'Asparagus'),
('name', 'LT',68, 'PRODUCT', 'Smidras'),
('name', 'EN',69, 'PRODUCT', 'Radish'),
('name', 'LT',69, 'PRODUCT', 'Ridikas'),
('name', 'EN',70, 'PRODUCT', 'Turnip'),
('name', 'LT',70, 'PRODUCT', 'Ropė'),
('name', 'EN',71, 'PRODUCT', 'Brussels Sprout'),
('name', 'LT',71, 'PRODUCT', 'Briuselio kopūstas'),
('name', 'EN',72, 'PRODUCT', 'Leek'),
('name', 'LT',72, 'PRODUCT', 'Poras'),
('name', 'EN',73, 'PRODUCT', 'Parsnip'),
('name', 'LT',73, 'PRODUCT', 'Pastarnokas'),
('name', 'EN',74, 'PRODUCT', 'Cauliflower'),
('name', 'LT',74, 'PRODUCT', 'Žiedinis kopūstas'),
('name', 'EN',75, 'PRODUCT', 'Beetroot'),
('name', 'LT',75, 'PRODUCT', 'Burokėlis'),
('name', 'EN',76, 'PRODUCT', 'Kale'),
('name', 'LT',76, 'PRODUCT', 'Lapinis kopūstas'),
('name', 'EN',77, 'PRODUCT', 'Arugula'),
('name', 'LT',77, 'PRODUCT', 'Gražgarstė'),
('name', 'EN',78, 'PRODUCT', 'Basil'),
('name', 'LT',78, 'PRODUCT', 'Bazilikas'),
('name', 'EN',79, 'PRODUCT', 'Parsley'),
('name', 'LT',79, 'PRODUCT', 'Petražolė'),
('name', 'EN',80, 'PRODUCT', 'Coriander'),
('name', 'LT',80, 'PRODUCT', 'Kalendra'),
('name', 'EN',81, 'PRODUCT', 'Thyme'),
('name', 'LT',81, 'PRODUCT', 'Čiobrelis'),
('name', 'EN',82, 'PRODUCT', 'Rosemary'),
('name', 'LT',82, 'PRODUCT', 'Rozmarinas'),
('name', 'EN',83, 'PRODUCT', 'Mint'),
('name', 'LT',83, 'PRODUCT', 'Mėta'),
('name', 'EN',84, 'PRODUCT', 'Oregano'),
('name', 'LT',84, 'PRODUCT', 'Raudonėlis'),
('name', 'EN',85, 'PRODUCT', 'Sage'),
('name', 'LT',85, 'PRODUCT', 'Šalavijas'),
('name', 'EN',86, 'PRODUCT', 'Clove'),
('name', 'LT',86, 'PRODUCT', 'Gvazdikėlis'),
('name', 'EN',87, 'PRODUCT', 'Cinnamon'),
('name', 'LT',87, 'PRODUCT', 'Cinamomas'),
('name', 'EN',88, 'PRODUCT', 'Nutmeg'),
('name', 'LT',88, 'PRODUCT', 'Muskatas'),
('name', 'EN',89, 'PRODUCT', 'Vanilla'),
('name', 'LT',89, 'PRODUCT', 'Vanilė'),
('name', 'EN',90, 'PRODUCT', 'Cocoa'),
('name', 'LT',90, 'PRODUCT', 'Kakava'),
('name', 'EN',91, 'PRODUCT', 'Chocolate'),
('name', 'LT',91, 'PRODUCT', 'Šokoladas'),
('name', 'EN',92, 'PRODUCT', 'Coffee'),
('name', 'LT',92, 'PRODUCT', 'Kava'),
('name', 'EN',93, 'PRODUCT', 'Tea'),
('name', 'LT',93, 'PRODUCT', 'Arbata'),
('name', 'EN',94, 'PRODUCT', 'Soda'),
('name', 'LT',94, 'PRODUCT', 'Gazuotas gėrimas'),
('name', 'EN',95, 'PRODUCT', 'Juice'),
('name', 'LT',95, 'PRODUCT', 'Sultys'),
('name', 'EN',96, 'PRODUCT', 'Water'),
('name', 'LT',96, 'PRODUCT', 'Vanduo'),
('name', 'EN',97, 'PRODUCT', 'Beer'),
('name', 'LT',97, 'PRODUCT', 'Alaus'),
('name', 'EN',98, 'PRODUCT', 'Wine'),
('name', 'LT',98, 'PRODUCT', 'Vynas'),
('name', 'EN',99, 'PRODUCT', 'Whiskey'),
('name', 'LT',99, 'PRODUCT', 'Viski'),
('name', 'EN',100, 'PRODUCT', 'Vodka'),
('name', 'LT',100, 'PRODUCT', 'Degtinė'),
('name', 'EN',101, 'PRODUCT', 'Gin'),
('name', 'LT',101, 'PRODUCT', 'Džinas'),
('name', 'EN',102, 'PRODUCT', 'Rum'),
('name', 'LT',102, 'PRODUCT', 'Romas'),
('name', 'EN',103, 'PRODUCT', 'Tofu'),
('name', 'LT',103, 'PRODUCT', 'Tofu'),
('name', 'EN',104, 'PRODUCT', 'Tempeh'),
('name', 'LT',104, 'PRODUCT', 'Tempeh'),
('name', 'EN',105, 'PRODUCT', 'Seitan'),
('name', 'LT',105, 'PRODUCT', 'Seitanas'),
('name', 'EN',106, 'PRODUCT', 'Almond'),
('name', 'LT',106, 'PRODUCT', 'Migdolas'),
('name', 'EN',107, 'PRODUCT', 'Cashew'),
('name', 'LT',107, 'PRODUCT', 'Anakardis'),
('name', 'EN',108, 'PRODUCT', 'Walnut'),
('name', 'LT',108, 'PRODUCT', 'Graikinis riešutas'),
('name', 'EN',109, 'PRODUCT', 'Pistachio'),
('name', 'LT',109, 'PRODUCT', 'Pistacija'),
('name', 'EN',110, 'PRODUCT', 'Hazelnut'),
('name', 'LT',110, 'PRODUCT', 'Lazdyno riešutas'),
('name', 'EN',111, 'PRODUCT', 'Peanut'),
('name', 'LT',111, 'PRODUCT', 'Žemės riešutas'),
('name', 'EN',112, 'PRODUCT', 'Chia Seed'),
('name', 'LT',112, 'PRODUCT', 'Čijos sėkla'),
('name', 'EN',113, 'PRODUCT', 'Flax Seed'),
('name', 'LT',113, 'PRODUCT', 'Lino sėkla'),
('name', 'EN',114, 'PRODUCT', 'Pumpkin Seed'),
('name', 'LT',114, 'PRODUCT', 'Moliūgų sėkla'),
('name', 'EN',115, 'PRODUCT', 'Sunflower Seed'),
('name', 'LT',115, 'PRODUCT', 'Saulėgrąžų sėkla'),
('name', 'EN',116, 'PRODUCT', 'Quinoa'),
('name', 'LT',116, 'PRODUCT', 'Bolivinė balanda'),
('name', 'EN',117, 'PRODUCT', 'Couscous'),
('name', 'LT',117, 'PRODUCT', 'Kuskusas'),
('name', 'EN',118, 'PRODUCT', 'Barley'),
('name', 'LT',118, 'PRODUCT', 'Miežiai'),
('name', 'EN',119, 'PRODUCT', 'Buckwheat'),
('name', 'LT',119, 'PRODUCT', 'Grikiai'),
('name', 'EN',120, 'PRODUCT', 'Oats'),
('name', 'LT',120, 'PRODUCT', 'Avižos'),
('name', 'EN',121, 'PRODUCT', 'Millet'),
('name', 'LT',121, 'PRODUCT', 'Soros'),
('name', 'EN',122, 'PRODUCT', 'Rye'),
('name', 'LT',122, 'PRODUCT', 'Rugiai'),
('name', 'EN',123, 'PRODUCT', 'Spelt'),
('name', 'LT',123, 'PRODUCT', 'Spelta'),
('name', 'EN',124, 'PRODUCT', 'Farro'),
('name', 'LT',124, 'PRODUCT', 'Farro'),
('name', 'EN',125, 'PRODUCT', 'Wheat Germ'),
('name', 'LT',125, 'PRODUCT', 'Kviečių gemalas'),
('name', 'EN',126, 'PRODUCT', 'Wheat Bran'),
('name', 'LT',126, 'PRODUCT', 'Kviečių sėlenos'),
('name', 'EN',127, 'PRODUCT', 'Cornmeal'),
('name', 'LT',127, 'PRODUCT', 'Kukurūzų miltai'),
('name', 'EN',128, 'PRODUCT', 'Polenta'),
('name', 'LT',128, 'PRODUCT', 'Polenta'),
('name', 'EN',129, 'PRODUCT', 'Tapioca'),
('name', 'LT',129, 'PRODUCT', 'Tapioka'),
('name', 'EN',130, 'PRODUCT', 'Arrowroot'),
('name', 'LT',130, 'PRODUCT', 'Marantas'),
('name', 'EN',131, 'PRODUCT', 'Gelatin'),
('name', 'LT',131, 'PRODUCT', 'Želatina'),
('name', 'EN',132, 'PRODUCT', 'Agar'),
('name', 'LT',132, 'PRODUCT', 'Agaras'),
('name', 'EN',133, 'PRODUCT', 'Miso'),
('name', 'LT',133, 'PRODUCT', 'Miso pasta'),
('name', 'EN',134, 'PRODUCT', 'Natto'),
('name', 'LT',134, 'PRODUCT', 'Nato'),
('name', 'EN',135, 'PRODUCT', 'Kimchi'),
('name', 'LT',135, 'PRODUCT', 'Kimči'),
('name', 'EN',136, 'PRODUCT', 'Sauerkraut'),
('name', 'LT',136, 'PRODUCT', 'Rauginti kopūstai'),
('name', 'EN',137, 'PRODUCT', 'Pickles'),
('name', 'LT',137, 'PRODUCT', 'Marinuoti agurkai'),
('name', 'EN',138, 'PRODUCT', 'Mustard'),
('name', 'LT',138, 'PRODUCT', 'Garstyčios'),
('name', 'EN',139, 'PRODUCT', 'Ketchup'),
('name', 'LT',139, 'PRODUCT', 'Kečupas'),
('name', 'EN',140, 'PRODUCT', 'Mayonnaise'),
('name', 'LT',140, 'PRODUCT', 'Majonezas'),
('name', 'EN',141, 'PRODUCT', 'Vinegar'),
('name', 'LT',141, 'PRODUCT', 'Actas'),
('name', 'EN',142, 'PRODUCT', 'Soy Sauce'),
('name', 'LT',142, 'PRODUCT', 'Sojų padažas'),
('name', 'EN',143, 'PRODUCT', 'Hot Sauce'),
('name', 'LT',143, 'PRODUCT', 'Aštrus padažas'),
('name', 'EN',144, 'PRODUCT', 'BBQ Sauce'),
('name', 'LT',144, 'PRODUCT', 'BBQ padažas'),
('name', 'EN',145, 'PRODUCT', 'Pesto'),
('name', 'LT',145, 'PRODUCT', 'Pesto padažas'),
('name', 'EN',146, 'PRODUCT', 'Hummus'),
('name', 'LT',146, 'PRODUCT', 'Humusas'),
('name', 'EN',147, 'PRODUCT', 'Guacamole'),
('name', 'LT',147, 'PRODUCT', 'Gvakamolė'),
('name', 'EN',148, 'PRODUCT', 'Salsa'),
('name', 'LT',148, 'PRODUCT', 'Salsa padažas'),
('name', 'EN',149, 'PRODUCT', 'Relish'),
('name', 'LT',149, 'PRODUCT', 'Marinuotos daržovės'),
('name', 'EN',150, 'PRODUCT', 'Tapenade'),
('name', 'LT',150, 'PRODUCT', 'Tapanada'),
('name', 'EN',151, 'PRODUCT', 'Tzatziki'),
('name', 'LT',151, 'PRODUCT', 'Cadzikis'),
('name', 'EN',152, 'PRODUCT', 'Raita'),
('name', 'LT',152, 'PRODUCT', 'Raita'),
('name', 'EN',153, 'PRODUCT', 'Rice Cake'),
('name', 'LT',153, 'PRODUCT', 'Ryžių paplotėlis'),
('name', 'EN',154, 'PRODUCT', 'Puffed Wheat'),
('name', 'LT',154, 'PRODUCT', 'Pūsti kviečiai'),
('name', 'EN',155, 'PRODUCT', 'Bran Flakes'),
('name', 'LT',155, 'PRODUCT', 'Sėlenų dribsniai'),
('name', 'EN',156, 'PRODUCT', 'Granola'),
('name', 'LT',156, 'PRODUCT', 'Granola'),
('name', 'EN',157, 'PRODUCT', 'Muesli'),
('name', 'LT',157, 'PRODUCT', 'Miuslis'),
('name', 'EN',158, 'PRODUCT', 'Protein Bar'),
('name', 'LT',158, 'PRODUCT', 'Baltymų batonėlis'),
('name', 'EN',159, 'PRODUCT', 'Energy Drink'),
('name', 'LT',159, 'PRODUCT', 'Energetinis gėrimas'),
('name', 'EN',160, 'PRODUCT', 'Protein Powder'),
('name', 'LT',160, 'PRODUCT', 'Baltymų milteliai'),
('name', 'EN',161, 'PRODUCT', 'Whey Protein'),
('name', 'LT',161, 'PRODUCT', 'Išrūgų baltymai'),
('name', 'EN',162, 'PRODUCT', 'Plant Protein'),
('name', 'LT',162, 'PRODUCT', 'Augaliniai baltymai'),
('name', 'EN',163, 'PRODUCT', 'Cereal Bar'),
('name', 'LT',163, 'PRODUCT', 'Grūdų batonėlis'),
('name', 'EN',164, 'PRODUCT', 'Trail Mix'),
('name', 'LT',164, 'PRODUCT', 'Užkandžių mišinys'),
('name', 'EN',165, 'PRODUCT', 'Dried Apricot'),
('name', 'LT',165, 'PRODUCT', 'Džiovintas abrikosas'),
('name', 'EN',166, 'PRODUCT', 'Raisin'),
('name', 'LT',166, 'PRODUCT', 'Razina'),
('name', 'EN',167, 'PRODUCT', 'Prune'),
('name', 'LT',167, 'PRODUCT', 'Džiovinta slyva'),
('name', 'EN',168, 'PRODUCT', 'Dried Fig'),
('name', 'LT',168, 'PRODUCT', 'Džiovinta figa'),
('name', 'EN',169, 'PRODUCT', 'Cranberry'),
('name', 'LT',169, 'PRODUCT', 'Spanguolė'),
('name', 'EN',170, 'PRODUCT', 'Date Paste'),
('name', 'LT',170, 'PRODUCT', 'Datulių pasta'),
('name', 'EN',171, 'PRODUCT', 'Molasses'),
('name', 'LT',171, 'PRODUCT', 'Melasa'),
('name', 'EN',172, 'PRODUCT', 'Maple Syrup'),
('name', 'LT',172, 'PRODUCT', 'Klevų sirupas'),
('name', 'EN',173, 'PRODUCT', 'Agave Syrup'),
('name', 'LT',173, 'PRODUCT', 'Agavų sirupas'),
('name', 'EN',174, 'PRODUCT', 'Cane Sugar'),
('name', 'LT',174, 'PRODUCT', 'Cukranendrių cukrus'),
('name', 'EN',175, 'PRODUCT', 'Brown Sugar'),
('name', 'LT',175, 'PRODUCT', 'Rudasis cukrus'),
('name', 'EN',176, 'PRODUCT', 'Icing Sugar'),
('name', 'LT',176, 'PRODUCT', 'Cukraus pudra'),
('name', 'EN',177, 'PRODUCT', 'Coconut Sugar'),
('name', 'LT',177, 'PRODUCT', 'Kokosų cukrus'),
('name', 'EN',178, 'PRODUCT', 'Palm Sugar'),
('name', 'LT',178, 'PRODUCT', 'Palmių cukrus'),
('name', 'EN',179, 'PRODUCT', 'Stevia'),
('name', 'LT',179, 'PRODUCT', 'Stevija'),
('name', 'EN',180, 'PRODUCT', 'Erythritol'),
('name', 'LT',180, 'PRODUCT', 'Eritritolis'),
('name', 'EN',181, 'PRODUCT', 'Xylitol'),
('name', 'LT',181, 'PRODUCT', 'Ksilitolis'),
('name', 'EN',182, 'PRODUCT', 'Sorbitol'),
('name', 'LT',182, 'PRODUCT', 'Sorbitolis'),
('name', 'EN',183, 'PRODUCT', 'Aspartame'),
('name', 'LT',183, 'PRODUCT', 'Aspartamas'),
('name', 'EN',184, 'PRODUCT', 'Sucralose'),
('name', 'LT',184, 'PRODUCT', 'Sukralozė'),
('name', 'EN',185, 'PRODUCT', 'Monk Fruit'),
('name', 'LT',185, 'PRODUCT', 'Vienuolio vaisius'),
('name', 'EN',186, 'PRODUCT', 'Yacon Syrup'),
('name', 'LT',186, 'PRODUCT', 'Jakono sirupas'),
('name', 'EN',187, 'PRODUCT', 'Ghee'),
('name', 'LT',187, 'PRODUCT', 'Ghi sviestas'),
('name', 'EN',188, 'PRODUCT', 'Lard'),
('name', 'LT',188, 'PRODUCT', 'Kiaulienos taukai'),
('name', 'EN',189, 'PRODUCT', 'Shortening'),
('name', 'LT',189, 'PRODUCT', 'Kepimo riebalai'),
('name', 'EN',190, 'PRODUCT', 'Tallow'),
('name', 'LT',190, 'PRODUCT', 'Jautienos taukai'),
('name', 'EN',191, 'PRODUCT', 'Coconut Oil'),
('name', 'LT',191, 'PRODUCT', 'Kokosų aliejus'),
('name', 'EN',192, 'PRODUCT', 'Palm Oil'),
('name', 'LT',192, 'PRODUCT', 'Palmių aliejus'),
('name', 'EN',193, 'PRODUCT', 'Canola Oil'),
('name', 'LT',193, 'PRODUCT', 'Rapsų aliejus'),
('name', 'EN',194, 'PRODUCT', 'Avocado Oil'),
('name', 'LT',194, 'PRODUCT', 'Avokadų aliejus'),
('name', 'EN',195, 'PRODUCT', 'Grapeseed Oil'),
('name', 'LT',195, 'PRODUCT', 'Vynuogių kauliukų aliejus'),
('name', 'EN',196, 'PRODUCT', 'Sesame Oil'),
('name', 'LT',196, 'PRODUCT', 'Sezamų aliejus'),
('name', 'EN',197, 'PRODUCT', 'Walnut Oil'),
('name', 'LT',197, 'PRODUCT', 'Graikinių riešutų aliejus'),
('name', 'EN',198, 'PRODUCT', 'Almond Oil'),
('name', 'LT',198, 'PRODUCT', 'Migdolų aliejus'),
('name', 'EN',199, 'PRODUCT', 'Macadamia Oil'),
('name', 'LT',199, 'PRODUCT', 'Makadamijų aliejus'),
('name', 'EN',200, 'PRODUCT', 'Hemp Oil'),
('name', 'LT',200, 'PRODUCT', 'Kanapių aliejus');